spring:
  application:
    name: gymbuddy-workout-runner
  jpa:
    hibernate:
      ddl-auto: none
      show_sql: true
      format_sql: true
    defer-datasource-initialization: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/gymbuddy}
    username: ${DB_USER}
    password: ${DB_PWD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  mvc:
    format:
      date-time: iso

mybatis:
  mapper-locations: "query/queries.xml"
  configuration:
    map-underscore-to-camel-case: true

firebase:
  audience: ${FIREBASE_PROJECT_ID:gymbuddy-b4e20}
  issuer: ${FIREBASE_ISSUER:https://securetoken.google.com/gymbuddy-b4e20}
  public-key-provider: ${FIREBASE_KEYS_URL:https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com}

server:
  port: 8080